# Generated by Django 3.1.4 on 2020-12-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
    ]
